/**
 * lib/beats.js — AUTONOMIC BEATS: the pure worklist substrate + registry (Slice 1 → Slice 2).
 *
 * A BEAT is a broad, hardwired coverage mandate (per docs/AUTONOMIC_ARCHITECTURE_DESIGN.md). The system
 * DECOMPOSES a beat into an enumerable WORKLIST of researchable targets; the existing directed-research
 * machinery then EXHAUSTS that bounded list (per-target deepen → mark covered → stop when all covered —
 * main.js runDirectedResearchPass), which fixes the loop-and-wander: a bounded, enumerated checklist can
 * neither loop (it knows what's done) nor wander (targets aren't model-invented). Coverage = covered/N.
 *
 * This module is the PURE half — the universe enumeration + target construction + the beat registry — so
 * it's fully offline testable. The orchestration (seed a directed focus with the worklist, kick the driver)
 * lives in main.js (seedBeatRun) because it needs generateResearchPlan + the driver.
 *
 * Slice 2 generalizes Slice 1's FL-only static roster to ALL states via the bundled Census county gazetteer
 * (lib/us_counties.json, generated by scripts/gen_us_counties.js from the authoritative national county
 * file — functioning county governments only, so CT/RI which have none are correctly absent). It also adds
 * the parent-beat registry the scheduler interleaves.
 *
 * Research runs BROWSER-first and every finding is corroborated (official sources are leads, not facts) —
 * those disciplines live in the directed-research pass, not here. This module only decides WHAT to cover.
 */
'use strict';

// Authoritative, bundled enumeration: { <USPS>: { name, noun, counties: [official county-equivalent names] } }.
// "noun" is the county-equivalent word for the state (Louisiana=parish, Alaska=borough, Puerto Rico=municipio).
const US_COUNTIES = require('./us_counties.json');
// The MUNICIPAL tier: { <USPS>: { name, places: [official incorporated-place names] } }. Generated by
// scripts/gen_us_places.js from the Census national place-by-county file (incorporated places only — the
// ones with an elected city/town/village council; CDPs are statistical, no government). New England towns
// are Census county-subdivisions (a separate future tier), so CT/RI/MA municipalities are under-counted here.
const US_PLACES = require('./us_places.json');

// Back-compat: the Slice-1 exports were STATE_COUNTIES/STATE_NAMES. Derive them from the gazetteer so anything
// still importing them keeps working (STATE_COUNTIES now carries the full official names, not bare tokens).
const STATE_NAMES = Object.fromEntries(Object.entries(US_COUNTIES).map(([k, v]) => [k, v.name]));
const STATE_COUNTIES = Object.fromEntries(Object.entries(US_COUNTIES).map(([k, v]) => [k, v.counties]));

// The four hardwired parent beats — Lucas's standing mandate. COMPLETENESS beats have a bounded, enumerable
// roster (measurable %, converges + is maintained); TOPIC beats gather continuously (freshness/volume, no
// finite universe). The scheduler (Slice 2c) interleaves these; sub-beats are the concrete worklists.
const PARENT_BEATS = [
  { id: 'elected-officials', kind: 'completeness', title: 'Elected officials — every office, dog-catcher on up' },
  { id: 'ai', kind: 'topic', title: 'AI — development, on the horizon, companies, countries, people, ideas, debates' },
  { id: 'power-infrastructure', kind: 'topic', title: 'Power infrastructure — grid, generation, transmission, siting' },
  { id: 'datacenters', kind: 'topic', title: 'Datacenters — buildout, operators, siting, power draw' },
];

// States (incl. DC + territories) that have a functioning county-equivalent government to enumerate.
function listCountyStates() {
  return Object.keys(US_COUNTIES).sort();
}

// The distinctive place token — the county-equivalent name with its noun suffix stripped ("Alachua County"
// → "alachua", "Orleans Parish" → "orleans", "St. Louis city" → "st. louis"). Anchored to the END so mid-name
// words survive ("James City County" → "james city"). This is the coverage key + browse-leash token.
function placeKey(name) {
  return String(name || '')
    .toLowerCase()
    .replace(/\s+(county|parish|borough|census area|municipality|municipio|city|town|village|township)\.?$/i, '')
    .trim();
}

// The governing body's name for a county-equivalent. Official titles vary wildly (TX "Commissioners Court",
// IL "County Board", LA "Police Jury/Parish Council", AK "Borough Assembly", VA independent cities "City
// Council") — the target string just has to anchor a browser search and carry the place token; the research
// pass corroborates the ACTUAL body + its members. Derive from the name's suffix (most specific), not the
// state noun, so independent cities inside a county state get "City Council", not "Board of Commissioners".
function bodyLabel(name) {
  const n = String(name || '');
  if (/\bParish$/i.test(n)) return 'Parish Council';
  if (/\bBorough$/i.test(n)) return 'Borough Assembly';
  if (/\bCensus Area$/i.test(n)) return 'Borough and Census Area government';
  if (/\bMunicipality$/i.test(n)) return 'Municipality Assembly';
  if (/\bmunicipio$/i.test(n)) return 'Municipal Government';
  if (/\bcity$/i.test(n)) return 'City Council';
  return 'Board of County Commissioners';
}

// Enumerate the county-commission worklist for a state → researchable target strings. Each names the concrete
// governing body ("Board of County Commissioners of Alachua County, Florida") so the directed pass researches
// THAT (its current members), and the county + state tokens keep the browse leash on-domain.
function countyCommissionTargets(stateCode) {
  const code = String(stateCode || '').toUpperCase();
  const st = US_COUNTIES[code];
  if (!st || !st.counties || !st.counties.length) return [];
  return st.counties.map((name) => `${bodyLabel(name)} of ${name}, ${st.name}`);
}

// A county-commission beat descriptor (the shape the registry holds one of per state, and seedBeatRun
// consumes). `enumerate()` returns the worklist; `universeSize()` is the coverage denominator (X / N).
function countyCommissionBeat(stateCode) {
  const code = String(stateCode || '').toUpperCase();
  const st = US_COUNTIES[code];
  const stateName = (st && st.name) || code;
  const noun = (st && st.noun) || 'county';
  const nounPlural = noun === 'parish' ? 'parishes' : noun === 'municipio' ? 'municipios' : `${noun === 'borough' ? 'boroughs' : 'counties'}`;
  const targets = countyCommissionTargets(code);
  return {
    id: `county-commissions-${code.toLowerCase()}`,
    parentBeat: 'elected-officials',
    kind: 'entity',                          // roster of governing bodies + their members
    stateCode: code,
    // DOSSIER depth (Lucas 2026-07-18): don't waste a single search — every board gets a COMPLETE dossier,
    // not a shallow roster. The fixed facet plan below drives the deepen pass through members+A-grade contacts,
    // meetings/minutes, biographies, the governing charter, history, and committees; main.js takes the facet-
    // aware DEEP path per target (keeps deepening while facets are uncovered, up to the deep ceiling), and the
    // scheduler supplies diversity by rotating states — depth is never cut for speed.
    depth: 'dossier',
    facets: [
      'current members and their seats, each with FULL contact info — direct email, phone, office address, term dates — taken from the official .gov roster AND corroborated by a second independent source so each contact reaches an A-grade citation',
      'how each member is elected + term length + district vs at-large + the district map/boundaries',
      'meeting schedule + agendas + minutes (recent and archived) + how the public accesses the records',
      'member biographies — background, prior offices held, occupation, notable positions and votes',
      'the governing charter / enabling statute / bylaws and the board\'s formal powers and duties',
      'committees, subcommittees, and the board\'s appointments to other bodies',
      'ALL OTHER county-elected offices and their current holders + full contact info — sheriff, clerk of court / circuit clerk, property assessor / appraiser, tax collector / treasurer, district / state\'s attorney, coroner / medical examiner, supervisor of elections, surveyor, and elected judges',
      'jurisdiction history + notable recent actions, controversies, and decisions',
    ],
    goal: `Compile and keep current the county-level governing board for every ${noun} in ${stateName} — `
      + `all ${targets.length} ${nounPlural}, with each board's current members. Corroborate against independent `
      + `sources; official rosters are leads, not facts.`,
    enumerate: () => targets,
    universeSize: () => targets.length,
  };
}

// Every county-commission sub-beat under the elected-officials parent (one per county-governing state), sorted
// by state code. This is the decomposition the scheduler draws from.
function countyCommissionSubBeats() {
  return listCountyStates().map((code) => countyCommissionBeat(code));
}

// --- MUNICIPAL tier (elected-officials granularity: city/town/village governments) --------------------

function listPlaceStates() { return Object.keys(US_PLACES).sort(); }

// The governing body for an incorporated place, from its Census type suffix (town/village/borough/city).
// Like bodyLabel, the target string just anchors a browser search; the pass corroborates the actual body.
function placeBodyLabel(name) {
  const n = String(name || '');
  if (/\btown$/i.test(n)) return 'Town Council';
  if (/\bvillage$/i.test(n)) return 'Village Board';
  if (/\bborough$/i.test(n)) return 'Borough Council';
  if (/\btownship$/i.test(n)) return 'Township Board';
  if (/\b(municipality|pueblo)$/i.test(n)) return 'Municipal Council';
  return 'City Council';
}
// Strip the trailing Census type word from a place name for display ("Birmingham city" → "Birmingham").
function placeDisplayName(name) {
  return String(name || '').replace(/\s+(city|town|village|borough|township|municipality|pueblo)$/i, '').trim();
}

// Enumerate the municipal worklist for a state → "<body> of <place>, <state>" (e.g. "City Council of
// Birmingham, Alabama", "Town Council of Autaugaville, Alabama").
function municipalTargets(stateCode) {
  const code = String(stateCode || '').toUpperCase();
  const st = US_PLACES[code];
  if (!st || !st.places || !st.places.length) return [];
  return st.places.map((name) => `${placeBodyLabel(name)} of ${placeDisplayName(name)}, ${st.name}`);
}

// A municipal-government beat descriptor for a state (dossier depth, like county). Covers the city's elected
// council + mayor + the other city-elected offices, with the same A-grade-contact + meetings/charter/history
// discipline. Huge worklists (TX ~1,220, IL ~1,300) — the scheduler slices + rotates them like any beat.
function municipalBeat(stateCode) {
  const code = String(stateCode || '').toUpperCase();
  const st = US_PLACES[code];
  const stateName = (st && st.name) || code;
  const targets = municipalTargets(code);
  return {
    id: `municipalities-${code.toLowerCase()}`,
    parentBeat: 'elected-officials',
    kind: 'entity',
    stateCode: code,
    depth: 'dossier',
    facets: [
      'the mayor and every city/town/village council (or commission) member — each with FULL contact info (direct email, phone, office address, term) from the official municipal .gov site AND corroborated by a second independent source for an A-grade citation',
      'the form of government (mayor-council / council-manager / commission), how each seat is elected, terms, and wards vs at-large + ward map',
      'council meeting schedule + agendas + minutes (recent and archived) + how the public accesses records',
      'ALL OTHER city-elected or appointed principals + contacts — city manager/administrator, clerk, attorney, treasurer/finance director, police chief, fire chief',
      'the municipal charter / code of ordinances and the council\'s powers',
      'biographies of the elected officials + notable recent actions and votes',
    ],
    goal: `Compile and keep current the municipal government — mayor, council, and city-elected offices — for `
      + `every incorporated city, town, and village in ${stateName} (all ${targets.length} municipalities), each `
      + `with current officeholders and A-grade contacts. Corroborate against independent sources; official `
      + `rosters are leads, not facts.`,
    enumerate: () => targets,
    universeSize: () => targets.length,
  };
}

function municipalSubBeats() {
  return listPlaceStates().map((code) => municipalBeat(code));
}

// The full elected-officials decomposition the scheduler rotates over: the county tier + the municipal tier.
// (Federal, state-legislature, school-board, and special-district tiers are future additions to this list.)
function electedOfficialsSubBeats() {
  return countyCommissionSubBeats().concat(municipalSubBeats());
}

// The place key embedded in a target string ("Board of County Commissioners of Lee County, Florida" → "lee").
// Drop the trailing ", StateName", then take the segment after the LAST " of " and strip its noun suffix.
function targetPlaceKey(target) {
  const t = String(target || '');
  const beforeState = t.replace(/,\s*[^,]+$/, '');
  const idx = beforeState.toLowerCase().lastIndexOf(' of ');
  const name = idx >= 0 ? beforeState.slice(idx + 4) : beforeState;
  return placeKey(name);
}

// Coverage of a beat given the directed focus's `covered` list (fuzzy-matched to worklist targets so
// "Alachua County Commission" counts against "Board of County Commissioners of Alachua County, Florida").
function coverageOf(targets, covered) {
  const cov = (Array.isArray(covered) ? covered : []).map((c) => String(c || '').toLowerCase());
  let done = 0;
  const remaining = [];
  for (const t of (targets || [])) {
    const key = targetPlaceKey(t);
    const hit = key.length >= 3 && cov.some((c) => c.includes(key) || key.includes(c));
    if (hit) done += 1; else remaining.push(t);
  }
  return { done, total: (targets || []).length, remaining, pct: (targets && targets.length) ? Math.round((done / targets.length) * 100) : 0 };
}

// NEWS-ANCHORED MAINTENANCE (Slice 2d) — "news is instant, official sites update slowly, so news is a great
// anchor for new materials." Given a state's news headlines, return the county targets a governance CHANGE is
// reported for, so the scheduler can re-verify JUST those counties instead of waiting for the slow freshness
// sweep. A hit requires all three: the county's distinctive token, the county-equivalent noun (so "Orange
// County commissioner" matches but "orange juice" doesn't), and a change cue. Pure; the caller supplies the
// headlines (from the news lane) and applies the re-verify. Government claims are LEADS — a news match just
// schedules a corroborated re-check, it doesn't itself change the graph.
const CHANGE_CUE_RE = /\b(elect\w*|re-?elect\w*|appoint\w*|resign\w*|sworn|swear|inaugurat\w*|recall\w*|vacan\w*|oust\w*|removed?|unseat\w*|step(?:s|ped)?\s+down|took\s+office|new\s+commissioner|special\s+election|died|passed\s+away|indicted|arrested)\b/i;
function matchNewsToTargets(stateCode, headlines) {
  const code = String(stateCode || '').toUpperCase();
  const st = US_COUNTIES[code];
  if (!st) return [];
  const targets = countyCommissionTargets(code);
  const noun = st.noun || 'county';
  const items = (Array.isArray(headlines) ? headlines : [])
    .map((h) => `${(h && h.title) || ''} ${(h && h.summary) || ''}`.toLowerCase().trim())
    .filter(Boolean);
  if (!items.length) return [];
  const hits = [];
  for (const t of targets) {
    const key = targetPlaceKey(t);
    if (key.length < 4) continue;   // too-short tokens (Bay, Lee, Clay) are noise-prone in free news text
    if (items.some((x) => x.includes(key) && x.includes(noun) && CHANGE_CUE_RE.test(x))) hits.push(t);
  }
  return hits;
}

module.exports = {
  US_COUNTIES, US_PLACES, STATE_COUNTIES, STATE_NAMES, PARENT_BEATS, CHANGE_CUE_RE,
  listCountyStates, listPlaceStates, placeKey, bodyLabel, targetPlaceKey,
  placeBodyLabel, placeDisplayName,
  countyCommissionTargets, countyCommissionBeat, countyCommissionSubBeats,
  municipalTargets, municipalBeat, municipalSubBeats, electedOfficialsSubBeats,
  coverageOf, matchNewsToTargets,
};
