/**
 * lib/beats.js — AUTONOMIC BEATS: the pure worklist substrate + registry (Slice 1 → Slice 2).
 *
 * A BEAT is a broad, hardwired coverage mandate (per docs/AUTONOMIC_ARCHITECTURE_DESIGN.md). The system
 * DECOMPOSES a beat into an enumerable WORKLIST of researchable targets; the existing directed-research
 * machinery then EXHAUSTS that bounded list (per-target deepen → mark covered → stop when all covered —
 * main.js runDirectedResearchPass), which fixes the loop-and-wander: a bounded, enumerated checklist can
 * neither loop (it knows what's done) nor wander (targets aren't model-invented). Coverage = covered/N.
 *
 * This module is the PURE half — the universe enumeration + target construction + the beat registry — so
 * it's fully offline testable. The orchestration (seed a directed focus with the worklist, kick the driver)
 * lives in main.js (seedBeatRun) because it needs generateResearchPlan + the driver.
 *
 * Slice 2 generalizes Slice 1's FL-only static roster to ALL states via the bundled Census county gazetteer
 * (lib/us_counties.json, generated by scripts/gen_us_counties.js from the authoritative national county
 * file — functioning county governments only, so CT/RI which have none are correctly absent). It also adds
 * the parent-beat registry the scheduler interleaves.
 *
 * Research runs BROWSER-first and every finding is corroborated (official sources are leads, not facts) —
 * those disciplines live in the directed-research pass, not here. This module only decides WHAT to cover.
 */
'use strict';

// Authoritative, bundled enumeration: { <USPS>: { name, noun, counties: [official county-equivalent names] } }.
// "noun" is the county-equivalent word for the state (Louisiana=parish, Alaska=borough, Puerto Rico=municipio).
const US_COUNTIES = require('./us_counties.json');
// The MUNICIPAL tier: { <USPS>: { name, places: [official incorporated-place names] } }. Generated by
// scripts/gen_us_places.js from the Census national place-by-county file (incorporated places only — the
// ones with an elected city/town/village council; CDPs are statistical, no government). New England towns
// are Census county-subdivisions (a separate future tier), so CT/RI/MA municipalities are under-counted here.
const US_PLACES = require('./us_places.json');
// The TOWN/TOWNSHIP tier: { <USPS>: { name, subdivisions: [official MCD names] } }. Generated by
// scripts/gen_us_subdivisions.js from the Census county-subdivision file (CLASSFP=T1 functioning MCD
// governments only — New England towns, NY/WI towns, and Midwest townships — the sub-county governments the
// incorporated-place tier misses). Only the 20 MCD-government states have these.
const US_SUBDIVISIONS = require('./us_subdivisions.json');
// The SCHOOL-BOARD tier: { <USPS>: { name, districts: [official school-district names] } }. Generated by
// scripts/gen_us_school_districts.js from the Census national school-district file (every public LEA; the
// board of education is elected in the large majority — the dossier surfaces the few that are appointed).
const US_SCHOOL_DISTRICTS = require('./us_school_districts.json');

// Back-compat: the Slice-1 exports were STATE_COUNTIES/STATE_NAMES. Derive them from the gazetteer so anything
// still importing them keeps working (STATE_COUNTIES now carries the full official names, not bare tokens).
const STATE_NAMES = Object.fromEntries(Object.entries(US_COUNTIES).map(([k, v]) => [k, v.name]));
const STATE_COUNTIES = Object.fromEntries(Object.entries(US_COUNTIES).map(([k, v]) => [k, v.counties]));

// The four hardwired parent beats — Lucas's standing mandate. COMPLETENESS beats have a bounded, enumerable
// roster (measurable %, converges + is maintained); TOPIC beats gather continuously (freshness/volume, no
// finite universe). The scheduler (Slice 2c) interleaves these; sub-beats are the concrete worklists.
const PARENT_BEATS = [
  { id: 'elected-officials', kind: 'completeness', title: 'Elected officials — every office, dog-catcher on up' },
  { id: 'ai', kind: 'topic', title: 'AI — development, on the horizon, companies, countries, people, ideas, debates' },
  { id: 'power-infrastructure', kind: 'topic', title: 'Power infrastructure — grid, generation, transmission, siting' },
  { id: 'datacenters', kind: 'topic', title: 'Datacenters — buildout, operators, siting, power draw' },
];

// States (incl. DC + territories) that have a functioning county-equivalent government to enumerate.
function listCountyStates() {
  return Object.keys(US_COUNTIES).sort();
}

// The distinctive place token — the county-equivalent name with its noun suffix stripped ("Alachua County"
// → "alachua", "Orleans Parish" → "orleans", "St. Louis city" → "st. louis"). Anchored to the END so mid-name
// words survive ("James City County" → "james city"). This is the coverage key + browse-leash token.
function placeKey(name) {
  return String(name || '')
    .toLowerCase()
    .replace(/\s+(county|parish|borough|census area|municipality|municipio|city|town|village|township)\.?$/i, '')
    .trim();
}

// The governing body's name for a county-equivalent. Official titles vary wildly (TX "Commissioners Court",
// IL "County Board", LA "Police Jury/Parish Council", AK "Borough Assembly", VA independent cities "City
// Council") — the target string just has to anchor a browser search and carry the place token; the research
// pass corroborates the ACTUAL body + its members. Derive from the name's suffix (most specific), not the
// state noun, so independent cities inside a county state get "City Council", not "Board of Commissioners".
function bodyLabel(name) {
  const n = String(name || '');
  if (/\bParish$/i.test(n)) return 'Parish Council';
  if (/\bBorough$/i.test(n)) return 'Borough Assembly';
  if (/\bCensus Area$/i.test(n)) return 'Borough and Census Area government';
  if (/\bMunicipality$/i.test(n)) return 'Municipality Assembly';
  if (/\bmunicipio$/i.test(n)) return 'Municipal Government';
  if (/\bcity$/i.test(n)) return 'City Council';
  return 'Board of County Commissioners';
}

// Enumerate the county-commission worklist for a state → researchable target strings. Each names the concrete
// governing body ("Board of County Commissioners of Alachua County, Florida") so the directed pass researches
// THAT (its current members), and the county + state tokens keep the browse leash on-domain.
function countyCommissionTargets(stateCode) {
  const code = String(stateCode || '').toUpperCase();
  const st = US_COUNTIES[code];
  if (!st || !st.counties || !st.counties.length) return [];
  return st.counties.map((name) => `${bodyLabel(name)} of ${name}, ${st.name}`);
}

// A county-commission beat descriptor (the shape the registry holds one of per state, and seedBeatRun
// consumes). `enumerate()` returns the worklist; `universeSize()` is the coverage denominator (X / N).
function countyCommissionBeat(stateCode) {
  const code = String(stateCode || '').toUpperCase();
  const st = US_COUNTIES[code];
  const stateName = (st && st.name) || code;
  const noun = (st && st.noun) || 'county';
  const nounPlural = noun === 'parish' ? 'parishes' : noun === 'municipio' ? 'municipios' : `${noun === 'borough' ? 'boroughs' : 'counties'}`;
  const targets = countyCommissionTargets(code);
  return {
    id: `county-commissions-${code.toLowerCase()}`,
    parentBeat: 'elected-officials',
    kind: 'entity',                          // roster of governing bodies + their members
    stateCode: code,
    // DOSSIER depth (Lucas 2026-07-18): don't waste a single search — every board gets a COMPLETE dossier,
    // not a shallow roster. The fixed facet plan below drives the deepen pass through members+A-grade contacts,
    // meetings/minutes, biographies, the governing charter, history, and committees; main.js takes the facet-
    // aware DEEP path per target (keeps deepening while facets are uncovered, up to the deep ceiling), and the
    // scheduler supplies diversity by rotating states — depth is never cut for speed.
    depth: 'dossier',
    facets: [
      'current members and their seats, each with FULL contact info — direct email, phone, office address, term dates — taken from the official .gov roster AND corroborated by a second independent source so each contact reaches an A-grade citation',
      'how each member is elected + term length + district vs at-large + the district map/boundaries',
      'meeting schedule + agendas + minutes (recent and archived) + how the public accesses the records',
      'member biographies — background, prior offices held, occupation, notable positions and votes',
      'the governing charter / enabling statute / bylaws and the board\'s formal powers and duties',
      'committees, subcommittees, and the board\'s appointments to other bodies',
      'ALL OTHER county-elected offices and their current holders + full contact info — sheriff, clerk of court / circuit clerk, property assessor / appraiser, tax collector / treasurer, district / state\'s attorney, coroner / medical examiner, supervisor of elections, surveyor, and elected judges',
      'jurisdiction history + notable recent actions, controversies, and decisions',
    ],
    goal: `Compile and keep current the county-level governing board for every ${noun} in ${stateName} — `
      + `all ${targets.length} ${nounPlural}, with each board's current members. Corroborate against independent `
      + `sources; official rosters are leads, not facts.`,
    enumerate: () => targets,
    universeSize: () => targets.length,
  };
}

// Every county-commission sub-beat under the elected-officials parent (one per county-governing state), sorted
// by state code. This is the decomposition the scheduler draws from.
function countyCommissionSubBeats() {
  return listCountyStates().map((code) => countyCommissionBeat(code));
}

// --- MUNICIPAL tier (elected-officials granularity: city/town/village governments) --------------------

function listPlaceStates() { return Object.keys(US_PLACES).sort(); }

// The governing body for an incorporated place, from its Census type suffix (town/village/borough/city).
// Like bodyLabel, the target string just anchors a browser search; the pass corroborates the actual body.
function placeBodyLabel(name) {
  const n = String(name || '');
  if (/\btown$/i.test(n)) return 'Town Council';
  if (/\bvillage$/i.test(n)) return 'Village Board';
  if (/\bborough$/i.test(n)) return 'Borough Council';
  if (/\btownship$/i.test(n)) return 'Township Board';
  if (/\b(municipality|pueblo)$/i.test(n)) return 'Municipal Council';
  return 'City Council';
}
// Strip the trailing Census type word from a place name for display ("Birmingham city" → "Birmingham").
function placeDisplayName(name) {
  return String(name || '').replace(/\s+(city|town|village|borough|township|municipality|pueblo)$/i, '').trim();
}

// Enumerate the municipal worklist for a state → "<body> of <place>, <state>" (e.g. "City Council of
// Birmingham, Alabama", "Town Council of Autaugaville, Alabama").
function municipalTargets(stateCode) {
  const code = String(stateCode || '').toUpperCase();
  const st = US_PLACES[code];
  if (!st || !st.places || !st.places.length) return [];
  return st.places.map((name) => `${placeBodyLabel(name)} of ${placeDisplayName(name)}, ${st.name}`);
}

// A municipal-government beat descriptor for a state (dossier depth, like county). Covers the city's elected
// council + mayor + the other city-elected offices, with the same A-grade-contact + meetings/charter/history
// discipline. Huge worklists (TX ~1,220, IL ~1,300) — the scheduler slices + rotates them like any beat.
function municipalBeat(stateCode) {
  const code = String(stateCode || '').toUpperCase();
  const st = US_PLACES[code];
  const stateName = (st && st.name) || code;
  const targets = municipalTargets(code);
  return {
    id: `municipalities-${code.toLowerCase()}`,
    parentBeat: 'elected-officials',
    kind: 'entity',
    stateCode: code,
    depth: 'dossier',
    facets: [
      'the mayor and every city/town/village council (or commission) member — each with FULL contact info (direct email, phone, office address, term) from the official municipal .gov site AND corroborated by a second independent source for an A-grade citation',
      'the form of government (mayor-council / council-manager / commission), how each seat is elected, terms, and wards vs at-large + ward map',
      'council meeting schedule + agendas + minutes (recent and archived) + how the public accesses records',
      'ALL OTHER city-elected or appointed principals + contacts — city manager/administrator, clerk, attorney, treasurer/finance director, police chief, fire chief',
      'the municipal charter / code of ordinances and the council\'s powers',
      'biographies of the elected officials + notable recent actions and votes',
    ],
    goal: `Compile and keep current the municipal government — mayor, council, and city-elected offices — for `
      + `every incorporated city, town, and village in ${stateName} (all ${targets.length} municipalities), each `
      + `with current officeholders and A-grade contacts. Corroborate against independent sources; official `
      + `rosters are leads, not facts.`,
    enumerate: () => targets,
    universeSize: () => targets.length,
  };
}

function municipalSubBeats() {
  return listPlaceStates().map((code) => municipalBeat(code));
}

// --- TOWN / TOWNSHIP tier (New England towns + Midwest townships — the MCD governments) -----------

function listSubdivisionStates() { return Object.keys(US_SUBDIVISIONS).sort(); }

// The governing body for an MCD, from its Census type suffix. New England towns run by a Board of Selectmen /
// Select Board (some by Town Council); NY/WI towns by a Town Board; Midwest townships by a Township Board of
// Trustees. The target string just anchors the search; the pass corroborates the actual body.
function subdivisionBodyLabel(name) {
  const n = String(name || '');
  if (/charter township$/i.test(n)) return 'Charter Township Board of Trustees';
  if (/township$/i.test(n)) return 'Township Board of Trustees';
  if (/plantation$/i.test(n)) return 'Plantation Board of Assessors';
  return 'Town Board / Select Board';   // towns (New England / NY / WI)
}
function subdivisionDisplayName(name) {
  return String(name || '').replace(/\s+(charter township|township|town|plantation|village|city|borough)$/i, '').trim();
}

function subdivisionTargets(stateCode) {
  const code = String(stateCode || '').toUpperCase();
  const st = US_SUBDIVISIONS[code];
  if (!st || !st.subdivisions || !st.subdivisions.length) return [];
  return st.subdivisions.map((name) => `${subdivisionBodyLabel(name)} of ${subdivisionDisplayName(name)}, ${st.name}`);
}

function subdivisionBeat(stateCode) {
  const code = String(stateCode || '').toUpperCase();
  const st = US_SUBDIVISIONS[code];
  const stateName = (st && st.name) || code;
  const targets = subdivisionTargets(code);
  return {
    id: `townships-${code.toLowerCase()}`,
    parentBeat: 'elected-officials',
    kind: 'entity',
    stateCode: code,
    depth: 'dossier',
    facets: [
      'the town/township governing board — every elected member (selectmen / trustees / town board) with FULL contact info (office address, phone, email) to an A-grade cited standard from the official town .gov AND corroborated',
      'the form of government (open town meeting / representative town meeting / town council / township trustees), how each seat is elected, and terms',
      'meeting schedule + agendas + minutes (recent and archived) + how the public accesses records',
      'ALL OTHER elected town offices + holders — town clerk, treasurer/tax collector, assessor(s), moderator, constable, highway commissioner',
      'the town charter / bylaws / ordinances and the board\'s powers',
      'biographies of the elected officials + notable recent actions',
    ],
    goal: `Compile and keep current the town/township government for every functioning town and township in `
      + `${stateName} (all ${targets.length}), each with its elected board and A-grade contacts. Corroborate `
      + `against independent sources; official rosters are leads, not facts.`,
    enumerate: () => targets,
    universeSize: () => targets.length,
  };
}

function subdivisionSubBeats() {
  return listSubdivisionStates().map((code) => subdivisionBeat(code));
}

// --- SCHOOL-BOARD tier (every public school district's elected board of education) ----------------

function listSchoolStates() { return Object.keys(US_SCHOOL_DISTRICTS).sort(); }

// Enumerate a state's school districts as dossier targets. "Board of Education of <district>" puts the
// distinctive district name after the last " of " so the coverage key lands on the district, not "Education".
function schoolBoardTargets(stateCode) {
  const code = String(stateCode || '').toUpperCase();
  const st = US_SCHOOL_DISTRICTS[code];
  if (!st || !st.districts || !st.districts.length) return [];
  return st.districts.map((name) => `Board of Education of ${name}, ${st.name}`);
}

function schoolBoardBeat(stateCode) {
  const code = String(stateCode || '').toUpperCase();
  const st = US_SCHOOL_DISTRICTS[code];
  const stateName = (st && st.name) || code;
  const targets = schoolBoardTargets(code);
  return {
    id: `school-boards-${code.toLowerCase()}`,
    parentBeat: 'elected-officials',
    kind: 'entity',
    stateCode: code,
    depth: 'dossier',
    facets: [
      'every board-of-education / school-board member with FULL contact info (email, phone, term, seat/zone) to an A-grade cited standard from the official district .gov AND corroborated',
      'how the board is selected — ELECTED (most) vs appointed — plus term length, number of seats, and any zones/at-large split',
      'the superintendent and senior administration + how the board is reached',
      'board meeting schedule + agendas + minutes (recent and archived) + how the public participates',
      'district profile — enrollment, schools, budget, and boundaries',
      'board policies, notable recent votes, and controversies',
    ],
    goal: `Compile and keep current the elected board of education for every public school district in `
      + `${stateName} (all ${targets.length}), each with current members and A-grade contacts. Corroborate `
      + `against independent sources; official rosters are leads, not facts.`,
    enumerate: () => targets,
    universeSize: () => targets.length,
  };
}

function schoolBoardSubBeats() {
  return listSchoolStates().map((code) => schoolBoardBeat(code));
}

// --- TOPIC / CONCEPT beats (AI, power infrastructure, datacenters) --------------------------------
//
// The OTHER beat kind. Completeness beats converge on a finite roster and stay done until a slow freshness
// sweep; TOPIC beats cover a curated worklist of SUB-TOPICS, then re-activate FAST (news moves) to keep the
// concept map current. They reuse the deep DOSSIER + REFUSAL research path (each sub-topic is deep-dived to
// exhaustion and decomposed into concept + entity nodes), so "topic" is expressed by the worklist + a short
// maintenance interval + a scheduler lane, not a different research engine. Lucas's standing frontiers:
// "AI (development, on the horizon, companies, countries, people, ideas, debates, everything), power
// infrastructure, datacenters." Browser-first, corroborated — official/company claims are leads, not facts.

const TOPIC_FACETS = [
  'the CURRENT STATE — what it is, the key organizations, people, and countries involved, and the very latest developments (news-anchored)',
  'the technology / mechanics / economics — how it actually works and what drives it',
  'the major DEBATES, open questions, controversies, and competing viewpoints',
  'key numbers — capabilities, capacity, scale, funding, metrics — and their trajectory',
  'policy, regulation, and geopolitics across the major jurisdictions (US, EU, China)',
  'ON THE HORIZON — near-term roadmap, likely next moves, and what to watch',
  'primary sources and evidence (papers, filings, official data, credible reporting)',
];

const TOPIC_BEAT_DEFS = {
  ai: {
    title: 'AI — development, horizon, companies, countries, people, ideas, debates',
    subtopics: [
      'frontier AI labs and their flagship models (OpenAI, Anthropic, Google DeepMind, Meta, xAI, Mistral, DeepSeek)',
      'the latest AI model releases, benchmarks, and capabilities',
      'AI compute and chips — Nvidia, TPUs, custom silicon, and supply constraints',
      'AI safety, alignment, interpretability, and evaluations',
      'AI policy and regulation — US executive actions, the EU AI Act, China, and state laws',
      'open-source and open-weight AI models and their ecosystem',
      'AI agents, tooling, and applications by sector',
      'AI funding, company formation, and market structure',
      'leading AI researchers, founders, and organizations',
      'AGI timelines, scaling debates, and research frontiers on the horizon',
      'AI\'s impact on jobs, the economy, and society',
      'AI risks, incidents, misuse, and security',
    ],
  },
  'power-infrastructure': {
    title: 'Power infrastructure — grid, generation, transmission, siting',
    subtopics: [
      'the US electric grid, the ISOs/RTOs, and how it is operated',
      'the generation mix — natural gas, nuclear, wind, solar, hydro, coal',
      'transmission projects, interconnection queues, and bottlenecks',
      'grid reliability, outages, and extreme-weather stress',
      'energy policy, FERC, and the state public-utility commissions',
      'the major utilities and grid operators',
      'battery and grid-scale energy storage',
      'nuclear power — SMRs, new builds, restarts, and uprates',
      'electricity demand growth from electrification and datacenters',
      'permitting, siting, and community opposition to energy infrastructure',
      'grid technology — HVDC, grid-enhancing technologies, and interconnection reform',
    ],
  },
  datacenters: {
    title: 'Datacenters — buildout, operators, siting, power draw',
    subtopics: [
      'the hyperscale operators (AWS, Azure, Google, Meta, Oracle) and their footprints',
      'datacenter buildout, capex, and the construction pipeline',
      'datacenter power demand and the strain on the grid',
      'cooling, water use, and efficiency (PUE)',
      'AI datacenter design and large GPU clusters',
      'colocation, wholesale, and datacenter REITs',
      'regional datacenter hubs — Northern Virginia, Texas, Phoenix, Ohio, Georgia',
      'datacenter siting, permitting, and community opposition',
      'datacenter power sourcing — nuclear deals, PPAs, and on-site generation',
      'submarine cables, connectivity, and the network backbone',
    ],
  },
};

const TOPIC_MAINTENANCE_MS = 3 * 24 * 60 * 60 * 1000;   // news moves fast — re-verify a converged topic every ~3 days

function listTopics() { return Object.keys(TOPIC_BEAT_DEFS); }

function topicBeat(topicId) {
  const id = String(topicId || '').toLowerCase();
  const def = TOPIC_BEAT_DEFS[id];
  if (!def) return null;
  const targets = def.subtopics.slice();
  return {
    id: `topic-${id}`,
    parentBeat: id,
    lane: 'topic',                    // scheduler weights the topic lane so concepts get fair time vs the elected tiers
    kind: 'entity',                   // deep research path (NOT the one-pass-per-aspect topical path)
    // CONCEPT depth (not 'dossier'/refusal): a topic sub-topic ("frontier AI labs") is inherently broad and
    // NEVER runs dry, so pure-refusal would grind one sub-topic forever and starve the other 11 + the rotation
    // (the 20-min audit caught exactly this). 'concept' = deep but facet-capped (~12 passes/sub-topic, still
    // ~30k chars) so the beat PROGRESSES through its whole worklist; news-maintenance re-visits each later.
    depth: 'concept',
    maintenanceMs: TOPIC_MAINTENANCE_MS,
    facets: TOPIC_FACETS.slice(),
    goal: `Continuously develop and keep current a deep, corroborated concept map of ${def.title}. Work the `
      + `sub-topics one at a time, deep-diving each to exhaustion across its state, mechanics, debates, numbers, `
      + `policy, and horizon. Browser-first; corroborate everything — company and official claims are leads, not facts.`,
    enumerate: () => targets,
    universeSize: () => targets.length,
  };
}

function topicBeats() { return listTopics().map((id) => topicBeat(id)); }

// --- FEDERAL tier (President/VP + the full Congress) ---------------------------------------------

// 2020-apportionment US House seats per state (effective for the 2023-2033 congresses), total = 435. Used to
// enumerate every congressional district as its own dossier target.
const HOUSE_SEATS = {
  AL: 7, AK: 1, AZ: 9, AR: 4, CA: 52, CO: 8, CT: 5, DE: 1, FL: 28, GA: 14, HI: 2, ID: 2, IL: 17, IN: 9,
  IA: 4, KS: 4, KY: 6, LA: 6, ME: 2, MD: 8, MA: 9, MI: 13, MN: 8, MS: 4, MO: 8, MT: 2, NE: 3, NV: 4,
  NH: 2, NJ: 12, NM: 3, NY: 26, NC: 14, ND: 1, OH: 15, OK: 5, OR: 6, PA: 17, RI: 2, SC: 7, SD: 1, TN: 9,
  TX: 38, UT: 4, VT: 1, VA: 11, WA: 10, WV: 2, WI: 8, WY: 1,
};
// Non-voting House members for DC + the territories (their one elected federal legislator).
const HOUSE_DELEGATES = { DC: 'Delegate', PR: 'Resident Commissioner', AS: 'Delegate', GU: 'Delegate', MP: 'Delegate', VI: 'Delegate' };

// Enumerate every elected FEDERAL office as a dossier target: the executive, all 100 senators (senior/junior
// per state), and all 435 representatives (by district; single-district states are "At-Large") + delegates.
function federalTargets() {
  const targets = ['President of the United States', 'Vice President of the United States'];
  for (const code of Object.keys(HOUSE_SEATS).sort()) {
    const stateName = STATE_NAMES[code] || code;
    targets.push(`Senior United States Senator from ${stateName}`);
    targets.push(`Junior United States Senator from ${stateName}`);
    const seats = HOUSE_SEATS[code];
    if (seats === 1) targets.push(`United States Representative for ${stateName}'s At-Large Congressional District`);
    else for (let d = 1; d <= seats; d++) targets.push(`United States Representative for ${stateName}'s ${d}${_ord(d)} Congressional District`);
  }
  for (const code of Object.keys(HOUSE_DELEGATES).sort()) {
    const stateName = STATE_NAMES[code] || code;
    targets.push(`${HOUSE_DELEGATES[code]} to the United States House of Representatives from ${stateName}`);
  }
  return targets;
}
function _ord(n) { const s = ['th', 'st', 'nd', 'rd'], v = n % 100; return s[(v - 20) % 10] || s[v] || s[0]; }

function federalBeat() {
  const targets = federalTargets();
  return {
    id: 'federal-officials',
    parentBeat: 'elected-officials',
    kind: 'entity',
    depth: 'dossier',
    facets: [
      'the current officeholder with FULL contact info — Washington DC office (address, phone), every district/state office, official webform and social — to an A-grade cited standard from the official .gov (senate.gov / house.gov / whitehouse.gov) AND corroborated by a second independent source',
      'committee and subcommittee assignments + any leadership, caucus, or party roles',
      'biography — background, prior offices, profession, education, military service',
      'term dates, seat class / next election, and electoral history + margins',
      'signature legislation, key votes, and stated policy positions',
      'senior staff (chief of staff, district director) and how constituents reach the office',
    ],
    goal: 'Compile and keep current every elected FEDERAL official — the President and Vice President, all 100 '
      + 'US Senators, all 435 Representatives, and the territorial delegates — each with current officeholder, '
      + 'A-grade contacts, committees, and record. Corroborate against independent sources; official pages are leads.',
    enumerate: () => targets,
    universeSize: () => targets.length,
  };
}

// --- STATE LEGISLATURE tier (every chamber's full membership) -------------------------------------

// Lower-chamber name by state (default "House of Representatives"). Nebraska is UNICAMERAL (one nonpartisan
// chamber, "the Legislature"), so it has a single target.
const STATE_LOWER_CHAMBER = {
  CA: 'State Assembly', NV: 'State Assembly', NY: 'State Assembly', WI: 'State Assembly',
  NJ: 'General Assembly',
  VA: 'House of Delegates', WV: 'House of Delegates', MD: 'House of Delegates',
};
const UNICAMERAL = { NE: 'Nebraska Legislature (unicameral)' };

// Enumerate a state's legislative chambers as dossier targets — each chamber's target deep-dives its COMPLETE
// current membership (every seat), so this is granular in content without assuming a district-numbering scheme.
function stateLegTargets(stateCode) {
  const code = String(stateCode || '').toUpperCase();
  const stateName = STATE_NAMES[code];
  if (!stateName) return [];
  if (UNICAMERAL[code]) return [UNICAMERAL[code]];
  const lower = STATE_LOWER_CHAMBER[code] || 'House of Representatives';
  return [`${stateName} State Senate`, `${stateName} ${lower}`];
}

function stateLegBeat(stateCode) {
  const code = String(stateCode || '').toUpperCase();
  const stateName = STATE_NAMES[code] || code;
  const targets = stateLegTargets(code);
  return {
    id: `state-legislature-${code.toLowerCase()}`,
    parentBeat: 'elected-officials',
    kind: 'entity',
    stateCode: code,
    depth: 'dossier',
    facets: [
      'the COMPLETE current membership roster — every member with district number, party, and FULL contact info (capitol office, district office, phone, email) to an A-grade cited standard from the official legislature .gov AND corroborated',
      'chamber leadership — presiding officer, majority and minority leaders, whips',
      'standing committees + their chairs and membership',
      'how members are elected, term length, chamber size, and the district map',
      'the current session — key bills, calendar, and how the public accesses proceedings and records',
      'member biographies and notable positions and votes',
    ],
    goal: `Compile and keep current every member of the ${stateName} state legislature — both chambers' complete `
      + `rosters with district, party, and A-grade contacts, plus leadership and committees. Corroborate against `
      + `independent sources; official rosters are leads, not facts.`,
    enumerate: () => targets,
    universeSize: () => targets.length,
  };
}

// States with a legislature to enumerate (all 50; DC/territories have their own councils, handled elsewhere).
function listLegislatureStates() { return Object.keys(HOUSE_SEATS).sort(); }
function stateLegSubBeats() { return listLegislatureStates().map((code) => stateLegBeat(code)); }

// The full elected-officials decomposition the scheduler rotates over, top down: FEDERAL → STATE LEGISLATURE →
// COUNTY (commission + row offices) → MUNICIPAL. (School-board, special-district, and New-England-town tiers
// are future additions to this list.) Registry order = rotation priority for never-run beats.
function electedOfficialsSubBeats() {
  return [federalBeat()]
    .concat(stateLegSubBeats())
    .concat(countyCommissionSubBeats())
    .concat(municipalSubBeats())
    .concat(subdivisionSubBeats())
    .concat(schoolBoardSubBeats());
}

// The place key embedded in a target string ("Board of County Commissioners of Lee County, Florida" → "lee").
// Drop the trailing ", StateName", then take the segment after the LAST " of " and strip its noun suffix.
function targetPlaceKey(target) {
  const t = String(target || '');
  const beforeState = t.replace(/,\s*[^,]+$/, '');
  const idx = beforeState.toLowerCase().lastIndexOf(' of ');
  const name = idx >= 0 ? beforeState.slice(idx + 4) : beforeState;
  return placeKey(name);
}

// Coverage of a beat given the directed focus's `covered` list (fuzzy-matched to worklist targets so
// "Alachua County Commission" counts against "Board of County Commissioners of Alachua County, Florida").
function coverageOf(targets, covered) {
  const cov = (Array.isArray(covered) ? covered : []).map((c) => String(c || '').toLowerCase());
  let done = 0;
  const remaining = [];
  for (const t of (targets || [])) {
    const key = targetPlaceKey(t);
    const hit = key.length >= 3 && cov.some((c) => c.includes(key) || key.includes(c));
    if (hit) done += 1; else remaining.push(t);
  }
  return { done, total: (targets || []).length, remaining, pct: (targets && targets.length) ? Math.round((done / targets.length) * 100) : 0 };
}

// NEWS-ANCHORED MAINTENANCE (Slice 2d) — "news is instant, official sites update slowly, so news is a great
// anchor for new materials." Given a state's news headlines, return the county targets a governance CHANGE is
// reported for, so the scheduler can re-verify JUST those counties instead of waiting for the slow freshness
// sweep. A hit requires all three: the county's distinctive token, the county-equivalent noun (so "Orange
// County commissioner" matches but "orange juice" doesn't), and a change cue. Pure; the caller supplies the
// headlines (from the news lane) and applies the re-verify. Government claims are LEADS — a news match just
// schedules a corroborated re-check, it doesn't itself change the graph.
const CHANGE_CUE_RE = /\b(elect\w*|re-?elect\w*|appoint\w*|resign\w*|sworn|swear|inaugurat\w*|recall\w*|vacan\w*|oust\w*|removed?|unseat\w*|step(?:s|ped)?\s+down|took\s+office|new\s+commissioner|special\s+election|died|passed\s+away|indicted|arrested)\b/i;
function matchNewsToTargets(stateCode, headlines) {
  const code = String(stateCode || '').toUpperCase();
  const st = US_COUNTIES[code];
  if (!st) return [];
  const targets = countyCommissionTargets(code);
  const noun = st.noun || 'county';
  const items = (Array.isArray(headlines) ? headlines : [])
    .map((h) => `${(h && h.title) || ''} ${(h && h.summary) || ''}`.toLowerCase().trim())
    .filter(Boolean);
  if (!items.length) return [];
  const hits = [];
  for (const t of targets) {
    const key = targetPlaceKey(t);
    if (key.length < 4) continue;   // too-short tokens (Bay, Lee, Clay) are noise-prone in free news text
    if (items.some((x) => x.includes(key) && x.includes(noun) && CHANGE_CUE_RE.test(x))) hits.push(t);
  }
  return hits;
}

module.exports = {
  US_COUNTIES, US_PLACES, STATE_COUNTIES, STATE_NAMES, PARENT_BEATS, CHANGE_CUE_RE,
  listCountyStates, listPlaceStates, placeKey, bodyLabel, targetPlaceKey,
  placeBodyLabel, placeDisplayName,
  countyCommissionTargets, countyCommissionBeat, countyCommissionSubBeats,
  municipalTargets, municipalBeat, municipalSubBeats,
  listSubdivisionStates, subdivisionBodyLabel, subdivisionDisplayName, subdivisionTargets, subdivisionBeat, subdivisionSubBeats,
  listSchoolStates, schoolBoardTargets, schoolBoardBeat, schoolBoardSubBeats,
  TOPIC_BEAT_DEFS, TOPIC_MAINTENANCE_MS, listTopics, topicBeat, topicBeats,
  HOUSE_SEATS, federalTargets, federalBeat,
  stateLegTargets, stateLegBeat, stateLegSubBeats, listLegislatureStates,
  electedOfficialsSubBeats,
  coverageOf, matchNewsToTargets,
};
