'use strict';
/**
 * lib/capability_manifest.js — the MEASURED capability manifest (run-2 F22, 2026-08-20).
 *
 * Live failure: asked for a scenario/polling run, she DENIED having python tools — five minutes
 * after running python in the R3 lane, with the Scenario Engine built and gate-smoked. The reply
 * layer's model of her own doors was "asserted, not measured": a static prompt line that never
 * mentioned the compute lanes, so the model guessed — and guessed no. The circuit-ledger rule
 * inverted: a refusal denied a door that exists.
 *
 * Cure: enumerate the doors by PROBING the registries (require the module, check the connection),
 * never by hand-written assertion. A door listed here EXISTS this boot — denials of listed doors
 * become impossible-by-construction at the prompt layer. Fail-absent: a probe error drops the
 * entry, an empty manifest prints nothing (never a fabricated list).
 *
 * W5 kinship: same organ pattern as the work-state vector — measured value, rendered expression.
 */

// Each entry: measured presence test + the door's honest one-phrase description. The tests are
// cheap requires/state reads; results are cached for 10 minutes (module presence doesn't churn).
const _PROBES = [
  { name: 'python one-off analysis (R3 lane)', probe: () => !!require('./analysis_lane').run || !!require('./analysis_lane'), detail: 'write and run a throwaway python analysis against your own data DBs (read-only) — campaign probabilities, polling extrapolations, any computation' },
  { name: 'scenario engine', probe: () => !!require('./scenario_engine'), detail: 'assert a hypothetical shock and replay the election sim under it — conditional what-ifs vs the live baseline' },
  { name: 'election forecast sim', probe: () => !!require('./forecast_sim'), detail: 'the live probabilistic election model (win probabilities, seat bands)' },
  { name: 'your own browser + web search', probe: () => !!require('./web').open, detail: 'open/read/act on pages in YOUR browser; search the live web' },
  { name: 'file workspace', probe: () => !!require('./files').dispatch, detail: 'read/write/list your persistent workspace (data/zoe_workspace) and read files anywhere on the machine' },
  { name: 'image generation', probe: () => !!require('./vision'), detail: 'render real images onto the canvas' },
  { name: 'canvas', probe: () => !!require('./canvas_docs').lastWriteTs, detail: 'land documents, tables, and images on the shared canvas' },
  { name: 'Echo research suite', probe: () => { const es = require('./echo_suit'); return !!(es && es.createSuit); }, detail: 'hundreds of grounded data/research tools (LegiScan, FEC, census, courts, news, agents you can delegate to) via your Echo connection' },
  { name: 'talking-head video', probe: () => require('./talking_head').available(), detail: 'render YOUR photoreal avatar (data/avatars/zoe_ref.jpg) speaking a voice WAV — offline lip-synced MP4 via lib/talking_head.render()' },
  { name: 'vertical video compose', probe: () => !!require('ffmpeg-static') && !!require('./video_compose').compose, detail: 'assemble a 1080x1920 short-form MP4 (your head video or a still + voice WAV + burned captions) via lib/video_compose.compose() — the talking-head output feeds straight into it' },
  { name: 'report graphics', probe: () => !!require('./report_graphics').render, detail: 'deterministic charts (bar/hbar/line), org charts, and schematics as SVG+PNG for documents via lib/report_graphics.render(spec) — you author the spec from GROUNDED data (the DB); this renderer never invents a number or a name, and diffusion image-gen is never used for data-bearing graphics' },
  { name: 'US report maps', probe: () => !!require('./report_graphics').render && require('./report_maps').available(), detail: 'US state/county maps on real census boundaries (choropleth/bubble, exact key resolution, honest no-data fill) via lib/report_graphics.render({kind:"map",...}) — geometry is measured-present this boot, never assumed' },
];

let _cache = null;
let _cacheTs = 0;
const CACHE_MS = 10 * 60 * 1000;

// The measured list: [{ name, detail }] — only doors whose probe PASSED this boot.
function manifest({ now = Date.now(), probes = _PROBES } = {}) {
  if (_cache && (now - _cacheTs) < CACHE_MS && probes === _PROBES) return _cache;
  const out = [];
  for (const p of probes) {
    try { if (p.probe()) out.push({ name: p.name, detail: p.detail }); } catch { /* fail-absent: an unprobeable door is not listed */ }
  }
  if (probes === _PROBES) { _cache = out; _cacheTs = now; }
  return out;
}

// The awareness line — rendered from the measured list; empty manifest → null (never fabricate).
function awarenessLine() {
  try {
    const m = manifest();
    if (!m.length) return null;
    const items = m.map((c) => `${c.name} — ${c.detail}`).join('; ');
    return `MEASURED CAPABILITY MANIFEST (generated by probing your own code registries this boot — every door listed here EXISTS and is yours right now; NEVER deny having one of these, and when you refuse something else, name the real door that covers it instead): ${items}.`;
  } catch { return null; }
}

module.exports = { manifest, awarenessLine, _PROBES };
