/* Test gate — runs every scripts/smoke_*.js through Electron-as-Node and reports aggregate
 * pass/fail. This is the regression gate for the memory/curation/retrieval work; run it before
 * any restart or after touching lib/ or main.js.
 *
 * Run: npm test   (or: node scripts/run_smokes.js)
 * This runner itself runs under plain Node — it only SPAWNS the smokes with the Electron binary
 * (so better-sqlite3's Electron-built ABI loads inside each child). It does not touch the DB.
 */
const { execFileSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const electron = require('electron');              // in plain Node this resolves to the binary path
const dir = __dirname;

// The GATE set: OFFLINE-DETERMINISTIC smokes only (isolated temp DB, no live model / network /
// Echo). The repo has ~120 smoke_*.js total, but many are live-integration (model/Echo/network)
// and can't run headless — running them all is always red and useless as a gate. This curated
// list is the regression suite for the memory / curation / retrieval / resilience work. Add a
// smoke here only once it's confirmed to pass offline with no external dependency.
const smokes = [
  'smoke_unprompted.js',
  'smoke_relevance_floor.js',
  'smoke_stream_watchdog.js',
  'smoke_email_killswitch.js',
  'smoke_cloud_curator.js',
  'smoke_self_evolution_merge.js',
  'smoke_neardup_knowledge.js',
  'smoke_graph_adjudicate.js',
  'smoke_daily_pass.js',
  'smoke_goal_guard.js',
  'smoke_verified_capture.js',
  'smoke_verified_reconcile.js',
  'smoke_verified_boost.js',
  'smoke_reconcile.js',
  'smoke_revise.js',
  'smoke_belief_correction.js',
  'smoke_iterate_block.js',
  'smoke_cloud_logic.js',
  'smoke_interests.js',
  'smoke_meta.js',
  'smoke_active_recall.js',
  'smoke_graph_walk.js',
  'smoke_idle_anchors.js',
  'smoke_curation_gate.js',
  'smoke_curation_store.js',
  'smoke_doc_decompose.js',
  'smoke_corroboration.js',
  'smoke_confidence_model.js',
  'smoke_confidence_decay.js',
  'smoke_decay_pass.js',
  'smoke_civic_domain.js',
  'smoke_promote_gate.js',
  'smoke_supersession.js',
  'smoke_identity_gate.js',
  'smoke_ingest_lane.js',
  'smoke_research_lane.js',
  'smoke_research_exec.js',
  'smoke_research_sources.js',
  'smoke_email_prefilter.js',
  'smoke_bounce_normalizer.js',
  'smoke_puller_bounce_ingest.js',
  'smoke_puller_revise.js',
  'smoke_puller_migration.js',
  'smoke_owner_identity.js',
  'smoke_identity_dedup.js',
  'smoke_puller_corrections.js',
  'smoke_certainty.js',
  'smoke_puller_supersession.js',
  'smoke_decomp_lane.js',
  'smoke_contact_extract.js',
  'smoke_contact_card.js',
  'smoke_puller_walk.js',
  'smoke_contacts_query.js',
  'smoke_prospect_fetch.js',
  'smoke_enrich_maigret.js',
  'smoke_sheet_extract.js',
  'smoke_file_ingest.js',
  'smoke_swirl_iterate.js',
  'smoke_live_info.js',
  'smoke_preferences.js',
  'smoke_personal_facts.js',
  'smoke_metacognition.js',
  'smoke_calibration_pressure.js',
  'smoke_focus.js',
  'smoke_condense.js',
  'smoke_assemble.js',
  'smoke_track.js',
  'smoke_track_index.js',
  'smoke_record_completeness.js',
  'smoke_records_interp.js',
  'smoke_research_plan.js',
  'smoke_compose.js',
  'smoke_canvas_ingest.js',
  'smoke_sources.js',
  'smoke_doc_qa.js',
  'smoke_doc_store.js',
  'smoke_promote.js',
  'smoke_retention.js',
  'smoke_meeting_lane.js',
  'smoke_meeting_audio.js',
  'smoke_localdb.js',
  'smoke_intake.js',
  'smoke_estimate_correction.js',
  'smoke_poll.js',
  'smoke_activity.js',
  'smoke_canvas_route.js',
  'smoke_leakguard.js',
  'smoke_research.js',
  'smoke_research_enrich.js',
  'smoke_known.js',
  'smoke_calendar.js',
  'smoke_self_dev.js',
  'smoke_self_state.js',
  'smoke_self_narrative.js',
  'smoke_mood.js',
  'smoke_voice.js',
  'smoke_personal.js',
  'smoke_reawaken.js',
  'smoke_vision.js',
  'smoke_vision_surfaces.js',
  'smoke_distill.js',
  'smoke_echo_cloud_route.js',
  'smoke_echo_tier.js',
  'smoke_tool_router.js',
  'smoke_echo_resolve.js',
  'smoke_subconscious.js',
  'smoke_extract_offload.js',
  'smoke_subconscious_tier.js',
  'smoke_model_sweep.js',
  'smoke_media_search_watch.js',
  'smoke_web_verify.js',
  'smoke_listen.js',
  'smoke_answer_draft.js',
  'smoke_turn_router.js',
  'smoke_tag_parser.js',
  'smoke_operator.js',
  'smoke_ner.js',
  'smoke_mention.js',
  'smoke_cognition.js',
  'smoke_intent_parse.js',
  'smoke_self_guardrail.js',
  'smoke_deep_budgets.js',
  'smoke_reasoning_headroom.js',
  'smoke_pipeline.js',
  'smoke_md_to_docx.js',
  'smoke_photo_grab.js',
  'smoke_face_match.js',
  'smoke_profile_confirm.js',
  'smoke_email_harvest.js',
  'smoke_tts.js',
  'smoke_tts_service.js',
  'smoke_concept_ground.js',
  'smoke_brainstorm.js',
  'smoke_usage_meter.js',
  'smoke_avatar_state.js',
  'smoke_vrm_state.js',
  'smoke_excavate.js',
  'smoke_staleness.js',
  // Data-Stream (news) lane — isolated NEWS_DB_PATH / pure; offline-deterministic
  'smoke_feeds_view.js',
  'smoke_news_store.js',
  'smoke_news_migrate.js',
  'smoke_news_poll.js',
  'smoke_news_watch.js',
  'smoke_news_lane.js',
  'smoke_news_claim.js',
  'smoke_news_objects.js',
  'smoke_news_brief.js',
  'smoke_news_ads.js',
  'smoke_video_capture.js',
  'smoke_video_reconstruct.js',
  'smoke_email_intake.js',
  'smoke_truth_poll.js',
  'smoke_news_topics.js',
  'smoke_news_rank.js',
  // Forecasting suite — Suite-A polling adapters (pure, offline-deterministic)
  'smoke_poll_wikipedia.js',
  'smoke_poll_votehub.js',
  'smoke_poll_538legacy.js',
  // Forecasting suite — Suite-B models (pure, offline-deterministic)
  'smoke_poll_average.js',
  'smoke_forecast_service.js',
  'smoke_forecast_sim.js',
  'smoke_news_feed.js',
  'smoke_forecast_reactor.js',
  'smoke_forecast_registry.js',
  'smoke_forecast_assess.js',
  'smoke_econ_feed.js',
  'smoke_forecast_fundamentals.js',
  'smoke_candidate_party.js',
  'smoke_seat_map.js',
  'smoke_sidecar.js',
  'smoke_coverage.js',
  'smoke_calibration.js',
  'smoke_backtest.js',
  'smoke_congress_backtest.js',
  'smoke_forecast_loop.js',
  // API management stream — catalog + authenticated client + management layer (pure, offline; mocked fetch/clock)
  'smoke_api_client.js',
  'smoke_api_manager.js',
  'smoke_api_stream.js',
  'smoke_api_landing.js',
  'smoke_api_bulk.js',
];

let passed = 0, failed = 0;
const failures = [];
for (const s of smokes) {
  let out = '';
  try {
    out = execFileSync(electron, [path.join(dir, s)], {
      env: { ...process.env, ELECTRON_RUN_AS_NODE: '1' },
      encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'], timeout: 300000,
    });
  } catch (e) { out = (e.stdout || '') + (e.stderr || ''); }
  const m = out.match(/(PASS|FAIL) — (\d+) ok, (\d+) failed/);
  if (m && m[1] === 'PASS') { passed++; console.log(`PASS  ${s.padEnd(30)} (${m[2]} ok)`); }
  else { failed++; failures.push(s); console.log(`FAIL  ${s.padEnd(30)} ${m ? `(${m[3]} failed)` : '(no result line — crashed?)'}`); }
}

console.log(`\n${failed === 0 ? '✅ ALL GREEN' : '❌ FAILURES'} — ${passed} suites passed, ${failed} failed`);
if (failures.length) console.log('   failed:', failures.join(', '));
process.exit(failed === 0 ? 0 : 1);
