"""
Office Document Generator — Create PPTX, DOCX, XLSX, and PDF files.

Uses python-pptx, python-docx, openpyxl, and fpdf for local document
generation. No API keys or external services required.
"""

from __future__ import annotations

import json
import logging
import os
import tempfile
from pathlib import Path

from app.tools._mcp_wrapper import _error

logger = logging.getLogger(__name__)

TOOL_DEF = {
    "name": "office_docs",
    "description": (
        "Generate professional office documents: presentations (PPTX), documents (DOCX), "
        "spreadsheets (XLSX), and PDFs. Provide structured content and get back a "
        "formatted file. Works fully offline with no API keys."
    ),
    "inputSchema": {
        "type": "object",
        "properties": {
            "doc_type": {
                "type": "string",
                "enum": ["pptx", "docx", "xlsx", "pdf"],
                "description": "Type of document to generate",
            },
            "title": {
                "type": "string",
                "description": "Document title",
                "default": "Untitled",
            },
            "content": {
                "type": "array",
                "description": (
                    "Document content as array of sections. Each section: "
                    "{heading: str, body: str, items: [str]} for docx/pdf; "
                    "{title: str, body: str, items: [str]} for pptx slides; "
                    "{headers: [str], rows: [[str]]} for xlsx sheets."
                ),
                "items": {"type": "object"},
            },
            "author": {
                "type": "string",
                "description": "Document author metadata",
                "default": "AURA",
            },
            "output_path": {
                "type": "string",
                "description": "Absolute path for the output file (auto-generated if omitted)",
            },
        },
        "required": ["doc_type", "content"],
    },
}


def _gen_pptx(title: str, content: list[dict], author: str, output_path: str) -> dict:
    """Generate a PowerPoint presentation."""
    try:
        from pptx import Presentation
        from pptx.util import Inches, Pt
    except ImportError:
        return _error("python-pptx not installed. Run: pip install python-pptx")

    prs = Presentation()
    prs.core_properties.title = title
    prs.core_properties.author = author

    # Title slide
    slide = prs.slides.add_slide(prs.slide_layouts[0])
    slide.shapes.title.text = title
    if slide.placeholders[1]:
        slide.placeholders[1].text = f"Generated by {author}"

    # Content slides
    for section in content:
        slide_title = section.get("title", section.get("heading", ""))
        body = section.get("body", "")
        items = section.get("items", [])

        if items:
            # Bullet slide
            slide = prs.slides.add_slide(prs.slide_layouts[1])
            slide.shapes.title.text = slide_title
            tf = slide.placeholders[1].text_frame
            tf.text = body if body else ""
            for item in items:
                p = tf.add_paragraph()
                p.text = item
                p.level = 0
        else:
            # Content slide
            slide = prs.slides.add_slide(prs.slide_layouts[1])
            slide.shapes.title.text = slide_title
            slide.placeholders[1].text = body

    prs.save(output_path)
    return {"output_path": output_path, "format": "pptx", "slides": len(prs.slides)}


def _gen_docx(title: str, content: list[dict], author: str, output_path: str) -> dict:
    """Generate a Word document."""
    try:
        from docx import Document
        from docx.shared import Pt
    except ImportError:
        return _error("python-docx not installed. Run: pip install python-docx")

    doc = Document()
    doc.core_properties.title = title
    doc.core_properties.author = author

    doc.add_heading(title, level=0)

    for section in content:
        heading = section.get("heading", section.get("title", ""))
        body = section.get("body", "")
        items = section.get("items", [])

        if heading:
            doc.add_heading(heading, level=1)
        if body:
            doc.add_paragraph(body)
        for item in items:
            doc.add_paragraph(item, style="List Bullet")

    doc.save(output_path)
    return {"output_path": output_path, "format": "docx", "sections": len(content)}


def _gen_xlsx(title: str, content: list[dict], author: str, output_path: str) -> dict:
    """Generate an Excel spreadsheet."""
    try:
        from openpyxl import Workbook
        from openpyxl.styles import Font
    except ImportError:
        return _error("openpyxl not installed. Run: pip install openpyxl")

    wb = Workbook()
    wb.properties.title = title
    wb.properties.creator = author

    # Remove default sheet if we have content
    if content:
        wb.remove(wb.active)

    for i, sheet_data in enumerate(content):
        sheet_name = sheet_data.get("heading", sheet_data.get("title", f"Sheet{i+1}"))[:31]
        ws = wb.create_sheet(title=sheet_name)

        headers = sheet_data.get("headers", [])
        rows = sheet_data.get("rows", [])

        if headers:
            for col, header in enumerate(headers, 1):
                cell = ws.cell(row=1, column=col, value=header)
                cell.font = Font(bold=True)

        start_row = 2 if headers else 1
        for row_idx, row_data in enumerate(rows):
            for col_idx, value in enumerate(row_data):
                ws.cell(row=start_row + row_idx, column=col_idx + 1, value=value)

    wb.save(output_path)
    return {"output_path": output_path, "format": "xlsx", "sheets": len(content)}


def _gen_pdf(title: str, content: list[dict], author: str, output_path: str) -> dict:
    """Generate a PDF document."""
    try:
        from fpdf import FPDF
    except ImportError:
        return _error("fpdf not installed. Run: pip install fpdf2")

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.set_author(author)
    pdf.set_title(title)

    # Title page
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 24)
    pdf.cell(0, 60, title, ln=True, align="C")
    pdf.set_font("Helvetica", "", 12)
    pdf.cell(0, 10, f"By {author}", ln=True, align="C")

    # Content
    for section in content:
        heading = section.get("heading", section.get("title", ""))
        body = section.get("body", "")
        items = section.get("items", [])

        if heading:
            pdf.add_page()
            pdf.set_font("Helvetica", "B", 16)
            pdf.cell(0, 12, heading, ln=True)
            pdf.ln(4)

        if body:
            pdf.set_font("Helvetica", "", 11)
            pdf.multi_cell(0, 6, body)
            pdf.ln(4)

        if items:
            pdf.set_font("Helvetica", "", 11)
            for item in items:
                pdf.cell(10)
                pdf.cell(0, 6, f"  {item}", ln=True)

    pdf.output(output_path)
    return {"output_path": output_path, "format": "pdf", "pages": pdf.page_no()}


async def tool_handler(inputs: dict) -> dict:
    doc_type = inputs.get("doc_type", "")
    if not doc_type:
        return _error("doc_type is required")

    content = inputs.get("content", [])
    if not content:
        return _error("content is required (array of sections)")

    title = inputs.get("title", "Untitled")
    author = inputs.get("author", "AURA")
    output_path = inputs.get("output_path", "")

    if not output_path:
        output_path = os.path.join(tempfile.gettempdir(), f"aura_doc.{doc_type}")

    generators = {
        "pptx": _gen_pptx,
        "docx": _gen_docx,
        "xlsx": _gen_xlsx,
        "pdf": _gen_pdf,
    }

    gen = generators.get(doc_type)
    if not gen:
        return _error(f"Unsupported doc_type: {doc_type}")

    return gen(title, content, author, output_path)
